version: '3.7'
services:
  db:
    image: mongo:4
    restart: always
    volumes:
      - ./docker-data/db:/data/db
    ports:
      - ${MONGO_OUTER_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
volumes:
  npm_cache:
  node_modules:
